# Generated by Django 4.1.7 on 2024-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Rate'),
        ),
    ]
